### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ttsirkia** [aidanhs/empython#1]
This is not a real issue, more like a roadmap question. Have you tried to compile any Python 3 version with Emscripten or do you have any plans to try? It would be great to have a real CPython3 in Javascript.

**Comment by aidanhs** [comment]
I doubt it'll be very difficult. I may try this weekend.

**Comment by gideongrinberg** [comment]
@aidanhs any luck with this?

**Comment by aidanhs** [comment]
I've updated to Python 3.5.9 on master and gh-pages branch - https://aidanhs.github.io/empython/
