### ISSUE TITLE
How was empython built

### ISSUE THREAD

**Issue by elvongray** [aidanhs/empython#2]
Hi @aidanhs 
I am curious on how empython was built. I also noticed I could not run the code on mac OS X.

**Comment by alanjds** [comment]
Here I got:

```
$ make -f ../Makefile prep
(...)
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  Parser/acceler.o Parser/grammar1.o Parser/listnode.o Parser/node.o Parser/parser.o Parser/parsetok.o Parser/bitset.o Parser/metagrammar.o Parser/firstsets.o Parser/grammar.o Parser/pgen.o Objects/obmalloc.o Python/mysnprintf.o Python/pyctype.o Parser/tokenizer_pgen.o Parser/printgrammar.o Parser/pgenmain.o -ldl  -framework CoreFoundation -o Parser/pgen
make[1]: Nothing to be done for `python'.
#cp Makefile ../Makefile.native
#cp Parser/pgen ../pgen.native
cp python ../python.native
cp: python is a directory (not copied).
make: *** [prep] Error 1
```

On OSX Mavericks. Anyone with better luck on other systems?

**Comment by aidanhs** [comment]
@alanjds are you on a case-insensitive filesystem?

**Comment by alanjds** [comment]
@aidanhs: I guess not.

**Comment by alanjds** [comment]
Mac OS Extended (Journaled)

**Comment by aidanhs** [comment]
In an empty directory can you try running `touch ABC && stat abc` and paste the output here?

The only cause I can think of that would cause your error message is case insensitivity, so I just want to double check. If it is case insensitivity then I'm not sure how much I'm going to be able to help given I don't have access to a machine like that.

If I created a Dockerfile so it builds reliably inside a container, would that be useful? I hear Docker on OSX is very good.

**Comment by alanjds** [comment]
Huh. Looks like my filesystem is case-insensive!

```
$ touch ABC && stat abc
16777218 36507177 -rw-r--r-- 1 alanjds wheel 0 0 "Aug 10 19:27:28 2016" "Aug 10 19:27:28 2016" "Aug 10 19:27:28 2016" "Aug 10 19:27:28 2016" 4096 0 0 abc
```

Well, if you can provide a Dockerfile I can run it happily

**Comment by aidanhs** [comment]
4 years layer, I've added some docker instructions!
